In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
image = torch.rand(6, 6)

print('Image = \n', image)

Image = 
 tensor([[0.8414, 0.8447, 0.8830, 0.1700, 0.4013, 0.9514],
        [0.0063, 0.3320, 0.7626, 0.1819, 0.8136, 0.6561],
        [0.3665, 0.3986, 0.9396, 0.9791, 0.5025, 0.9616],
        [0.3405, 0.3260, 0.1740, 0.5001, 0.9151, 0.4578],
        [0.1618, 0.6261, 0.6079, 0.3112, 0.6898, 0.7664],
        [0.2651, 0.7767, 0.1232, 0.1478, 0.5765, 0.2052]])


In [3]:
image = image.unsqueeze(dim=0)
image = image.unsqueeze(dim=0)

print('Image shape: ', image.shape)
print('Image: \n', image)

Image shape:  torch.Size([1, 1, 6, 6])
Image: 
 tensor([[[[0.8414, 0.8447, 0.8830, 0.1700, 0.4013, 0.9514],
          [0.0063, 0.3320, 0.7626, 0.1819, 0.8136, 0.6561],
          [0.3665, 0.3986, 0.9396, 0.9791, 0.5025, 0.9616],
          [0.3405, 0.3260, 0.1740, 0.5001, 0.9151, 0.4578],
          [0.1618, 0.6261, 0.6079, 0.3112, 0.6898, 0.7664],
          [0.2651, 0.7767, 0.1232, 0.1478, 0.5765, 0.2052]]]])


In [4]:
conv = nn.Conv2d(1, 3, kernel_size=(3, 3), bias=False)

In [5]:
outimage = conv(image)

print('OutImage shape = ', outimage.shape)
print('OutImage = \n', outimage)

OutImage shape =  torch.Size([1, 3, 4, 4])
OutImage = 
 tensor([[[[ 0.2235,  0.3227,  0.0215, -0.0692],
          [-0.3870, -0.2169, -0.0185, -0.3823],
          [ 0.0388, -0.0960,  0.1293,  0.0999],
          [-0.1435, -0.1858, -0.2065, -0.1780]],

         [[-0.3450, -0.3351, -0.4300, -0.3394],
          [-0.1092, -0.1282, -0.1250, -0.3497],
          [-0.1944, -0.3868, -0.3657, -0.1648],
          [-0.0308, -0.1883, -0.2047, -0.1111]],

         [[ 0.1938, -0.1679,  0.0933,  0.1886],
          [ 0.2053,  0.0995,  0.0414,  0.0903],
          [ 0.0247,  0.1045,  0.1600, -0.0094],
          [-0.0765,  0.0706,  0.2257, -0.0128]]]],
       grad_fn=<ConvolutionBackward0>)


In [6]:
class MyConv2d:
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0):
        self.kernels = torch.rand(out_channels, in_channels, kernel_size[0], kernel_size[1])
        self.out_channels = out_channels
        self.stride = stride
        self.padding = padding
    def convolve(self, x):
        return F.conv2d(x, self.kernels)

In [7]:
myconv = MyConv2d(1, 3, (3, 3))

In [8]:
outimage = myconv.convolve(image)

print('OutImage shape = ', outimage.shape)
print('OutImage = \n', outimage)

OutImage shape =  torch.Size([1, 3, 4, 4])
OutImage = 
 tensor([[[[2.3678, 3.1866, 2.9238, 2.9663],
          [1.6746, 2.4053, 3.3340, 3.2991],
          [2.0961, 2.3427, 2.5782, 3.2008],
          [1.7398, 2.0835, 2.0461, 2.2449]],

         [[2.2373, 2.1297, 2.5264, 2.4693],
          [1.7829, 2.0102, 2.3712, 2.9208],
          [1.6683, 2.2036, 2.3427, 2.3296],
          [1.3499, 1.5540, 1.9816, 1.8970]],

         [[3.0175, 2.8300, 2.9140, 3.0227],
          [2.1605, 2.4624, 2.9374, 3.3561],
          [2.1971, 2.6326, 2.9501, 3.1229],
          [1.9147, 1.5526, 2.3105, 2.5244]]]])
