In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
image = torch.rand(6, 6)

print('Image = \n', image)

Image = 
 tensor([[0.4456, 0.4011, 0.8302, 0.7384, 0.4079, 0.1627],
        [0.0504, 0.7576, 0.2124, 0.2411, 0.7417, 0.1898],
        [0.8516, 0.4527, 0.6020, 0.8988, 0.3174, 0.6074],
        [0.1424, 0.9761, 0.0659, 0.2700, 0.0252, 0.4630],
        [0.1924, 0.5014, 0.5550, 0.2047, 0.3048, 0.6525],
        [0.0074, 0.2670, 0.2803, 0.2601, 0.1140, 0.9288]])


In [3]:
image = image.unsqueeze(dim=0)

print('Image shape: ', image.shape)
print('Image: \n', image)

Image shape:  torch.Size([1, 6, 6])
Image: 
 tensor([[[0.4456, 0.4011, 0.8302, 0.7384, 0.4079, 0.1627],
         [0.0504, 0.7576, 0.2124, 0.2411, 0.7417, 0.1898],
         [0.8516, 0.4527, 0.6020, 0.8988, 0.3174, 0.6074],
         [0.1424, 0.9761, 0.0659, 0.2700, 0.0252, 0.4630],
         [0.1924, 0.5014, 0.5550, 0.2047, 0.3048, 0.6525],
         [0.0074, 0.2670, 0.2803, 0.2601, 0.1140, 0.9288]]])


In [4]:
conv = nn.Conv2d(1, 3, kernel_size=(3, 3), bias=False)

In [5]:
outimage = conv(image)

print('OutImage shape = ', outimage.shape)
print('OutImage = \n', outimage)

OutImage shape =  torch.Size([3, 4, 4])
OutImage = 
 tensor([[[-0.7921, -0.5342, -0.7305, -0.7333],
         [-0.3655, -0.4462, -0.3612, -0.1561],
         [-0.8727, -0.3013, -0.5865, -0.4509],
         [-0.4180, -0.4715, -0.0989, -0.3119]],

        [[ 0.6715,  0.2896,  0.4062,  0.5630],
         [-0.0750,  0.4828,  0.3203,  0.0345],
         [ 0.6724,  0.2045,  0.3750,  0.4468],
         [ 0.0911,  0.4517, -0.0242,  0.3537]],

        [[-0.0433,  0.2252,  0.2945, -0.0139],
         [ 0.1634,  0.1718,  0.0544,  0.2524],
         [ 0.0573,  0.3006,  0.1307,  0.3503],
         [ 0.1454,  0.1775,  0.0719,  0.1229]]], grad_fn=<SqueezeBackward1>)


In [6]:
class MyConv2d:
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0):
        self.kernels = torch.rand(out_channels, 1, in_channels, kernel_size[0], kernel_size[1])
        self.out_channels = out_channels
        self.stride = stride
        self.padding = padding
    def convolve(self, x):
        outputs = [F.conv2d(x, self.kernels[i], stride=self.stride, padding=self.padding) for i in range(self.out_channels)]
        return torch.concat(outputs, dim=0)

In [7]:
myconv = MyConv2d(1, 3, (3, 3))

In [8]:
outimage = myconv.convolve(image)

print('OutImage shape = ', outimage.shape)
print('OutImage = \n', outimage)

OutImage shape =  torch.Size([3, 4, 4])
OutImage = 
 tensor([[[2.4235, 2.1604, 2.0828, 1.7772],
         [1.8947, 1.6787, 1.8898, 1.1575],
         [2.1721, 1.9367, 1.1285, 1.4318],
         [1.1018, 1.3610, 0.7908, 1.4739]],

        [[3.0231, 3.2784, 2.8141, 2.4024],
         [2.4015, 2.4269, 2.0481, 2.2124],
         [2.5010, 2.6062, 1.8098, 2.1686],
         [1.8848, 1.5442, 1.1593, 2.3265]],

        [[1.9658, 2.0455, 2.5431, 2.0869],
         [1.6423, 2.0246, 1.1063, 1.4473],
         [2.0629, 1.6575, 1.7440, 1.7706],
         [1.4812, 1.5890, 0.7715, 1.2275]]])
