In [1]:
import torch
import torch.nn.functional as F

In [2]:
image = torch.rand(6, 6)

print('Image = \n', image)

Image = 
 tensor([[0.2250, 0.4065, 0.2362, 0.2412, 0.7866, 0.3665],
        [0.8201, 0.5112, 0.8441, 0.8183, 0.5256, 0.5728],
        [0.8804, 0.7539, 0.4890, 0.3048, 0.6855, 0.9855],
        [0.2825, 0.9261, 0.0604, 0.9401, 0.7487, 0.3663],
        [0.3871, 0.8796, 0.3820, 0.6901, 0.5056, 0.0546],
        [0.7680, 0.1354, 0.3098, 0.5496, 0.6725, 0.1073]])


In [3]:
image = image.unsqueeze(dim=0)

print('Image shape: ', image.shape)
print('Image: \n', image)

Image shape:  torch.Size([1, 6, 6])
Image: 
 tensor([[[0.2250, 0.4065, 0.2362, 0.2412, 0.7866, 0.3665],
         [0.8201, 0.5112, 0.8441, 0.8183, 0.5256, 0.5728],
         [0.8804, 0.7539, 0.4890, 0.3048, 0.6855, 0.9855],
         [0.2825, 0.9261, 0.0604, 0.9401, 0.7487, 0.3663],
         [0.3871, 0.8796, 0.3820, 0.6901, 0.5056, 0.0546],
         [0.7680, 0.1354, 0.3098, 0.5496, 0.6725, 0.1073]]])


In [4]:
kernel = torch.ones(3, 3)

print('Kernel = \n', kernel)

Kernel = 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
kernel = kernel.unsqueeze(dim=0)
kernel = kernel.unsqueeze(dim=0)

print('Kernel = \n', kernel)

Kernel = 
 tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [6]:
outimage = F.conv2d(image, kernel, stride=1, padding=0)
print('OutImage shape = ', outimage.shape)
print('OutImage = \n', outimage)

OutImage shape =  torch.Size([1, 4, 4])
OutImage = 
 tensor([[[5.1664, 4.6051, 4.9313, 5.2869],
         [5.5677, 5.6477, 5.4165, 5.9476],
         [5.0410, 5.4259, 4.8061, 5.2812],
         [4.1310, 4.8731, 4.8588, 4.6349]]])


In [7]:
for s in range(1, 4):
    outimage = F.conv2d(image, kernel, stride=s, padding=0)
    print('OutImage shape = ', outimage.shape)
    print('OutImage = \n', outimage)
    print('\n')

OutImage shape =  torch.Size([1, 4, 4])
OutImage = 
 tensor([[[5.1664, 4.6051, 4.9313, 5.2869],
         [5.5677, 5.6477, 5.4165, 5.9476],
         [5.0410, 5.4259, 4.8061, 5.2812],
         [4.1310, 4.8731, 4.8588, 4.6349]]])


OutImage shape =  torch.Size([1, 2, 2])
OutImage = 
 tensor([[[5.1664, 4.9313],
         [5.0410, 4.8061]]])


OutImage shape =  torch.Size([1, 2, 2])
OutImage = 
 tensor([[[5.1664, 5.2869],
         [4.1310, 4.6349]]])




In [8]:
for p in range(1, 4):
    outimage = F.conv2d(image, kernel, stride=1, padding=p)
    print('OutImage shape = ', outimage.shape)
    print('OutImage = \n', outimage)
    print('\n')

OutImage shape =  torch.Size([1, 6, 6])
OutImage = 
 tensor([[[1.9629, 3.0431, 3.0574, 3.4520, 3.3111, 2.2516],
         [3.5972, 5.1664, 4.6051, 4.9313, 5.2869, 3.9226],
         [4.1742, 5.5677, 5.6477, 5.4165, 5.9476, 3.8845],
         [4.1097, 5.0410, 5.4259, 4.8061, 5.2812, 3.3462],
         [3.3788, 4.1310, 4.8731, 4.8588, 4.6349, 2.4550],
         [2.1702, 2.8619, 2.9465, 3.1096, 2.5798, 1.3400]]])


OutImage shape =  torch.Size([1, 8, 8])
OutImage = 
 tensor([[[0.2250, 0.6316, 0.8677, 0.8839, 1.2640, 1.3944, 1.1531, 0.3665],
         [1.0452, 1.9629, 3.0431, 3.0574, 3.4520, 3.3111, 2.2516, 0.9393],
         [1.9256, 3.5972, 5.1664, 4.6051, 4.9313, 5.2869, 3.9226, 1.9248],
         [1.9831, 4.1742, 5.5677, 5.6477, 5.4165, 5.9476, 3.8845, 1.9246],
         [1.5501, 4.1097, 5.0410, 5.4259, 4.8061, 5.2812, 3.3462, 1.4064],
         [1.4377, 3.3788, 4.1310, 4.8731, 4.8588, 4.6349, 2.4550, 0.5283],
         [1.1551, 2.1702, 2.8619, 2.9465, 3.1096, 2.5798, 1.3400, 0.1619],
         [0

In [9]:
print('Number of parameters is ', kernel.numel())

Number of parameters is  9
